export const SERIES_CONFIG: Record<string, {
  name: string;
  subject: string;
  color: string;
  bgLight: string;
  border: string;
  text: string;
  emoji: string;
}> = {
  'time-travel': {
    name: 'タイムトラベル探偵団',
    subject: '歴史（社会科）',
    color: 'bg-amber-600',
    bgLight: 'bg-amber-50',
    border: 'border-amber-300',
    text: 'text-amber-800',
    emoji: '🕰️',
  },
  'literature': {
    name: '名作文学ミステリー',
    subject: '国語',
    color: 'bg-indigo-700',
    bgLight: 'bg-indigo-50',
    border: 'border-indigo-300',
    text: 'text-indigo-800',
    emoji: '📖',
  },
  'popculture': {
    name: 'マンガ教養ミステリー',
    subject: 'ポップカルチャー',
    color: 'bg-purple-600',
    bgLight: 'bg-purple-50',
    border: 'border-purple-300',
    text: 'text-purple-800',
    emoji: '🎭',
  },
  'math': {
    name: '数字の迷宮',
    subject: '算数',
    color: 'bg-emerald-600',
    bgLight: 'bg-emerald-50',
    border: 'border-emerald-300',
    text: 'text-emerald-800',
    emoji: '🔢',
  },
  'science': {
    name: 'サイエンス捜査班',
    subject: '理科',
    color: 'bg-blue-600',
    bgLight: 'bg-blue-50',
    border: 'border-blue-300',
    text: 'text-blue-800',
    emoji: '🔬',
  },
  'moral': {
    name: '答えのない法廷',
    subject: '道徳',
    color: 'bg-orange-600',
    bgLight: 'bg-orange-50',
    border: 'border-orange-300',
    text: 'text-orange-800',
    emoji: '⚖️',
  },
  'digital': {
    name: '情報モラル探偵団',
    subject: '情報モラル',
    color: 'bg-cyan-600',
    bgLight: 'bg-cyan-50',
    border: 'border-cyan-300',
    text: 'text-cyan-800',
    emoji: '💻',
  },
  'geography': {
    name: '地図探偵団',
    subject: '社会（地理）',
    color: 'bg-teal-600',
    bgLight: 'bg-teal-50',
    border: 'border-teal-300',
    text: 'text-teal-800',
    emoji: '🗺️',
  },
  'health': {
    name: '保健探偵団',
    subject: '保健',
    color: 'bg-rose-600',
    bgLight: 'bg-rose-50',
    border: 'border-rose-300',
    text: 'text-rose-800',
    emoji: '🏥',
  },
  'english': {
    name: '英語探偵団',
    subject: '英語',
    color: 'bg-sky-600',
    bgLight: 'bg-sky-50',
    border: 'border-sky-300',
    text: 'text-sky-800',
    emoji: '🔤',
  },
  'career': {
    name: 'キャリア探偵団',
    subject: 'キャリア',
    color: 'bg-lime-600',
    bgLight: 'bg-lime-50',
    border: 'border-lime-300',
    text: 'text-lime-800',
    emoji: '💼',
  },
  'esd': {
    name: 'ESD探偵団',
    subject: '環境',
    color: 'bg-green-600',
    bgLight: 'bg-green-50',
    border: 'border-green-300',
    text: 'text-green-800',
    emoji: '🌍',
  },
  'civics': {
    name: '公民探偵団',
    subject: '公民',
    color: 'bg-slate-600',
    bgLight: 'bg-slate-50',
    border: 'border-slate-300',
    text: 'text-slate-800',
    emoji: '🏛️',
  },
  'disaster': {
    name: '防災探偵団',
    subject: '防災',
    color: 'bg-red-600',
    bgLight: 'bg-red-50',
    border: 'border-red-300',
    text: 'text-red-800',
    emoji: '🚨',
  },
  'homeec': {
    name: '家庭科探偵団',
    subject: '家庭科',
    color: 'bg-pink-600',
    bgLight: 'bg-pink-50',
    border: 'border-pink-300',
    text: 'text-pink-800',
    emoji: '🧵',
  },
  'money': {
    name: 'お金の探偵団',
    subject: '金融教育',
    color: 'bg-yellow-600',
    bgLight: 'bg-yellow-50',
    border: 'border-yellow-300',
    text: 'text-yellow-800',
    emoji: '💰',
  },
  'programming': {
    name: 'プログラミング探偵団',
    subject: 'プログラミング',
    color: 'bg-violet-600',
    bgLight: 'bg-violet-50',
    border: 'border-violet-300',
    text: 'text-violet-800',
    emoji: '🖥️',
  },
  'math2': {
    name: '数学深化探偵団',
    subject: '数学',
    color: 'bg-emerald-700',
    bgLight: 'bg-emerald-50',
    border: 'border-emerald-300',
    text: 'text-emerald-800',
    emoji: '📐',
  },
};

export function getSeriesConfig(series: string) {
  return SERIES_CONFIG[series] || SERIES_CONFIG['time-travel'];
}
